### ISSUE TITLE
Install instructions for windows

### ISSUE THREAD

**Issue by Trisk3lion** [mrusme/kiwi#1]
Hello, I think this project looks really interesting but as someone who uses windows could you supply installation instructions for windows as well?

**Comment by mrusme** [comment]
@Trisk3lion unfortunately I cannot as I'm not using Windows myself. A quick search on Google however lead me to [this thread](https://unix.stackexchange.com/questions/477601/dd-an-image-onto-an-sd-card-from-ubuntu-in-windows-subsystem-for-linux).

Basically you could use the software proposed there to burn [the firmware](https://github.com/mrusme/kiwi/releases/download/v1.0.0/kiwi.fw.zip) onto an SD card, then remount the SD card in order to edit your wifi config and then you should be ready to go. :)

Hope this helps!
